scalar JSON
scalar Void
scalar Date

type User {
    id: Int!
    createdAt: Date!
    modifiedAt: Date!
    email: String!
    admin: Boolean!

    createdById: Int
    createdBy: User
}

type Activity {
    id: Int!
    createdAt: Date!
    createdBy: User!
    createdById: Int!
    message: String!
    dramaId: Int

    drama: Drama
}

type Tag {
    id: Int!
    createdAt: Date!
    createdBy: User!
    createdById: Int!
    name: String!

    createdByCurrentUser: Boolean
}

type Link {
    id: Int!
    createdAt: Date!
    createdBy: User!
    createdById: Int!
    url: String!
    title: String!
}

type Watched {
    id: Int!
    createdAt: Date!
    createdBy: User!
    createdById: Int!
    lastModifiedAt: Date!
    status: String
}

type GroupedTag {
    name: String!
    count: Int!
    current: Boolean!
}

type Drama {
    id: Int!
    createdAt: Date!
    createdBy: User!
    createdById: Int!
    status: String!
    lastModifiedBy: User!
    lastModifiedById: Int!
    lastModifiedAt: Date!
    title: String!
    description: String!
    startedAiringAt: Date
    finishedAiringAt: Date
    country: String
    episodeDuration: Int
    episodeCount: Int
    tags: [Tag!]!
    links: [Link!]!
    watched: [Watched!]!
    currentUserWatched: String
    groupedTags: [GroupedTag!]!
}

type PaginationInfo {
    count: Int!
    skip: Int
    take: Int
    total: Int!
}

type DramasQueryResponse {
    data: [Drama!]!
    meta: PaginationInfo!
}

type ActivityQueryResponse {
    data: [Activity!]!
    meta: PaginationInfo!
}

type Query {
    activity(
        where: JSON
        take: Int
        skip: Int
        orderBy: JSON
    ): ActivityQueryResponse!
    currentUser: User!
    drama(id: Int!): Drama
    dramas(
        where: JSON
        take: Int
        skip: Int
        orderBy: JSON
    ): DramasQueryResponse!
    isDramaBookmarked(url: String!): Int
    tags(where: JSON, take: Int, skip: Int): [Tag!]!
    users: [User!]!
    dump: JSON
}

input CreateDramaContent {
    title: String
    description: String
    tags: [String!]
    links: [String!]
    status: String
    watched: String
    episodeDuration: Int
    episodeCount: Int
    country: String
    startedAiringAt: Date
    finishedAiringAt: Date
}

input UpdateLinkContent {
    url: String!
}

input CreateUserInput {
    email: String!
    admin: Boolean
}

type Mutation {
    addDrama(input: CreateDramaContent!): Drama
    addUser(email: String!): User
    removeDrama(id: Int!): Void
    removeUser(email: String!): Void
    updateDrama(id: Int!, input: CreateDramaContent!): Void
}
